# -*- mode: python ; coding: utf-8 -*-
# Mac 版本专用 spec

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'markitdown',
        'markitdown._markitdown',
        'markitdown._base_converter',
        'markitdown._stream_info',
        'markitdown._exceptions',
        'markitdown.converters',
        'markitdown.converters._plain_text_converter',
        'markitdown.converters._html_converter',
        'markitdown.converters._pdf_converter',
        'markitdown.converters._docx_converter',
        'markitdown.converters._xlsx_converter',
        'markitdown.converters._pptx_converter',
        'markitdown.converters._image_converter',
        'markitdown.converters._audio_converter',
        'markitdown.converters._csv_converter',
        'markitdown.converters._zip_converter',
        'markitdown.converters._epub_converter',
        'markitdown.converters._rss_converter',
        'markitdown.converters._ipynb_converter',
        'markitdown.converters._outlook_msg_converter',
        'markitdown.converters._wikipedia_converter',
        'markitdown.converters._youtube_converter',
        'markitdown.converters._bing_serp_converter',
        'markitdown.converters._doc_intel_converter',
        'markitdown.converters._cu_converter',
        'magika',
        'onnxruntime',
        'PIL',
        'pdfminer',
        'pdfminer.high_level',
        'pdfplumber',
        'mammoth',
        'lxml',
        'lxml.etree',
        'openpyxl',
        'pandas',
        'python_pptx',
        'pptx',
        'pydub',
        'speech_recognition',
        'bs4',
        'markdownify',
        'charset_normalizer',
        'defusedxml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MarkItDown',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MarkItDown',
)
